/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidemo_jni_MyJni */

#ifndef _Included_com_example_androidemo_jni_MyJni
#define _Included_com_example_androidemo_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidemo_jni_MyJni
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidemo_jni_MyJni_getStrFromC
  (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif
#endif
